Repository oliveoil222/CS386-Project, pull requests merged in 2024-02, with the labels that each got.

#18 Adding a folder for the back end files to be stored in
  .DS_Store
  ssts/.DS_Store
  ssts/backendDB/grabInfo.py
  ssts/templates/.DS_Store
Labels: backend

#20 Last Commit to Main by Middleware
  ssts/__init__.py
Labels: enhancement, middleware

#45 Starting site
  Deliverables/D2Requirements.md
  Deliverables/Submitted/D2.md
  Deliverables/img/Hannah Diagram.png
  Deliverables/img/JaredDiagram.png
  Deliverables/img/OliviaDiagram.png
  Deliverables/img/Use Case Diagram.png
  Deliverables/img/issueTrackerD2.png
  ssts/__init__.py
  ssts/static/css/404_error.css
  ssts/static/css/form.css
  ssts/static/css/home.css
  ssts/static/css/login.css
  ssts/static/css/sidebar.css
  ssts/static/js/sidebar.js
  ssts/static/js/signup.js
  ssts/static/styles.css
  ssts/templates/auth/login.html
  ssts/templates/auth/signup.html
  ssts/templates/base.html
  ssts/templates/error/404.html
  ssts/templates/new/ticket.html
  ssts/ticket.py
Labels: enhancement, frontend
